### Create a new user
POST http://localhost:3000/signup
content-type: application/json

{
  "username": "test@test.com",
  "password": "12345678"
}

### Sign in as an existing user
POST http://localhost:3000/signin
content-type: application/json

{
  "username": "Mihawk_san",
  "password": "123456789"
}

### Get the currently signed in user
GET http://localhost:3000/users/whoami

### Sign out
POST http://localhost:3000/users/signout

### Find a particular user with a given ID
GET http://localhost:3000/users/4

### Find all users with a given username
GET http://localhost:3000/users
# GET http://localhost:3000/users?username=Mihawk_san

### Delete a user given id
DELETE http://localhost:3000/users/3

### Update a user
PATCH http://localhost:3000/users/4
content-type: application/json

{
  "password": "aaaaa"
}

### Add new Game
POST http://localhost:3000/games/new
Content-Type: application/json

{
  "title": "Borderlands 2",
  "description": "Classic shooting game with 3D visuals.",
  "genre": "Shooting",
  "platform": "PS3",
  "releaseDate": "2014-02-24"
}

### Get games by title
GET http://localhost:3000/games?title=Call%20Of%20Duty%204

### Get all games
GET http://localhost:3000/games

### Delete a game by id
DELETE http://localhost:3000/games/4


### Get all collections
GET http://localhost:3000/collections/1

### Get collection by Id


### Get a user's collection
GET http://localhost:3000/collections

### Create collection
POST http://localhost:3000/collections/new
Content-Type: application/json

{
  "playedGames": [{
  "title": "Call Of Duty 3",
  "description": "Classic shooting game with good visuals.",
  "genre": "Shooting",
  "platform": "PC",
  "releaseDate": "2014-02-24"
}],
  "playingGames": [{
  "title": "Call Of Duty 2",
  "description": "Classic shooting game with good visuals.",
  "genre": "Shooting",
  "platform": "PC",
  "releaseDate": "2014-02-24"
}],
  "plannedGames": [{
  "title": "Call Of Duty 1",
  "description": "Classic shooting game with good visuals.",
  "genre": "Shooting",
  "platform": "PC",
  "releaseDate": "2014-02-24"
}]
}