# USERS CONTROLLER ENDPOINTS --------------------------------

### Get the currently signed in user
GET http://localhost:3000/users/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXJuYW1lIjoidGVzdEB0ZXN0LmNvbSIsImlhdCI6MTcwNDk4NTMzOCwiZXhwIjoxNzA1MDcxNzM4fQ.lhpadXD4ky2_8xD6avXi6xNUw9YrysRNXvWwzhBIByk

### Get user by id
GET http://localhost:3000/users/1

### Find all users with a given username
GET http://localhost:3000/users
# GET http://localhost:3000/users?username=Mihawk_san

### Delete a user given id
DELETE http://localhost:3000/users/2


### Update a user
PATCH http://localhost:3000/users/6
content-type: application/json

{
  "password": "aaaaaaaa"
}






# {HAS NOT BEEN TESTED WELL}
# AUTH CONTROLLER ENDPOINTS -----------------------------------
### Create a new user
POST http://localhost:3000/signup
content-type: application/json

{
  "username": "Admin",
  "password": "12345678"
}

### Sign in as the new user
POST http://localhost:3000/signin
content-type: application/json

{
  "username": "test@test.com",
  "password": "12345678"
}

### Sign in as an existing user
POST http://localhost:3000/signin
content-type: application/json

{
  "username": "Admin",
  "password": "12345678"
}
###
POST http://localhost:3000/signout



# GAMES CONTROLLER ENDPOINTS -------------------------------------

### Add new Game
POST http://localhost:3000/games/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsInVzZXJuYW1lIjoiQWRtaW4iLCJpYXQiOjE3MDQ5ODk3ODksImV4cCI6MTcwNTA3NjE4OX0.Me4JE-nUOAIsmmi5zmvtJnp_oqe7d4Y-a9M-EDBTfoQ

{
  "title": "Borderlands 1",
  "description": "Classic shooting game with 3D visuals.",
  "genre": "Shooting",
  "publisher": "Bandai Namco",
  "imageUrl": "/images/borderlands-2.jpg",
  "platform": "PS3",
  "releaseDate": "2014-02-24"
}

### Get game by Id
GET http://localhost:3000/games/1

### Get all games
GET http://localhost:3000/games

### Get games by genre
GET http://localhost:3000/games?genre=Shooting

### Search a game
# DOESN'T WORK
GET http://localhost:3000/games/search/Borderlands%202

### Delete a game by id
DELETE http://localhost:3000/games/61
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsInVzZXJuYW1lIjoiQWRtaW4iLCJpYXQiOjE3MDQ5ODk3ODksImV4cCI6MTcwNTA3NjE4OX0.Me4JE-nUOAIsmmi5zmvtJnp_oqe7d4Y-a9M-EDBTfoQ

### Update a game
# DOESN'T WORK IF SOME PROPERTIES ARE MISSING. WORKS IF ALL ARE GIVEN.
#FIX: create an update DTO to make optional USING ?.
PATCH http://localhost:3000/games/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsInVzZXJuYW1lIjoiQWRtaW4iLCJpYXQiOjE3MDQ5ODk3ODksImV4cCI6MTcwNTA3NjE4OX0.Me4JE-nUOAIsmmi5zmvtJnp_oqe7d4Y-a9M-EDBTfoQ

{
  "title": "Assassin's Creed Origins",
    "description": "An action-adventure game set in ancient Egypt",
    "genre": "Action",
    "platform": "PlayStation 4, Xbox One, Windows",
    "publisher": "Ubisoft",
    "releaseDate": "2017-10-27",
    "imageUrl": "images/games/ac-origins.jpg"
}






# COLLECTIONS CONTROLLER ENDPOINTS --------------------------------------

### Create collection
POST http://localhost:3000/collections/new
Content-Type: application/json

{
  "userId": 3,
  "gameId": 1,
  "status": "PLANNED"
}

### Get collection by Id
GET http://localhost:3000/collections/1

### Get all collections
GET http://localhost:3000/collections

### Get collection by status
GET http://localhost:3000/collections?status=PLANNED

### Get an array of game objects using userId+status
# DOESN'T WORK
GET http://localhost:3000/collections/user/3?status=PLANNED

### Delete a collection by id
DELETE http://localhost:3000/collections/1

### Update a collection
# DOESN'T WORK IF SOME PROPERTIES ARE MISSING. WORKS IF ALL ARE GIVEN.
#FIX: create an update DTO to make optional USING ?.
PATCH http://localhost:3000/collections/2
Content-Type: application/json

{
  "status": "PLAYING",
  "gameId": 4,
  "userId": 3
}
